---
# tasks file for centos-demo
#
#
- name: configure repos
  block:
    - name: configure yum repos - comment out mirrorlist
      shell: "sed -i 's/^mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*"
    - name: configure yum repos - change baseurl
      shell: "sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*"
  when: repoconfig_bool == True  
- name: download red hat gpg key
  get_url:
    dest: "/etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release"
    url: "https://www.redhat.com/security/data/fd431d51.txt"
- name: download SSL cert for Red Hat CDN
  get_url:
    dest: "/etc/rhsm/ca/redhat-uep.pem"
    url: " https://ftp.redhat.com/redhat/convert2rhel/redhat-uep.pem"
- name: add the convert2rhel repo
  get_url:
    dest: "/etc/yum.repos.d/convert2rhel.repo"
    url: "https://ftp.redhat.com/redhat/convert2rhel/8/convert2rhel.repo"
- name: ensure supported kernel is installed
  yum:
    name: "{{ kernel_package }}"
    state: present
  notify: reboot_system
  when: upgrade_bool == True    
- name: install convert2rhel utility
  yum:
    name: "convert2rhel"
    state: latest
- name: upgrade all packages
  yum:
    name: '*'
    state: latest
  when: upgrade_bool == True    
- name: disable convert2rhel repo (this avoids a bug in convert2rhel tool)
  lineinfile:
    path: /etc/yum.repos.d/convert2rhel.repo
    regexp: "enabled = 1"
    line: "enabled = 0"
    state: present
- name: check if reboot required
  meta: flush_handlers
- name: perform conversion using Red Hat Satellite
  block:
    - name: download consumer rpm from satellite server
      get_url:
        dest: "/usr/share/convert2rhel/subscription-manager/katello-ca-consumer-latest.noarch.rpm"
        url: https://{{satellite_fqdn}}/pub/katello-ca-consumer-latest.noarch.rpm
        validate_certs: false
    - name: create config file for convert2rhel
      template:
        src: config.ini.j2
        dest: "/usr/share/convert2rhel/config.ini"
        mode: 0600
    - name: converting to RHEL (min. 20 mins)
      command: convert2rhel --org {{organisation}} --config-file /usr/share/convert2rhel/config.ini -y
      notify: reboot_system
  when: reboot_bool == True


